<?php

namespace AppBundle\Controller;

use PostBundle\Entity\Post;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AdminController as BaseAdminController;

class AdminController extends BaseAdminController
{
    public function prePersistEntity($entity)
    {
        if ($entity instanceof Post)
        {
            $entity->setUser($this->getUser());
        }
        parent::prePersistEntity($entity); // TODO: Change the autogenerated stub
    }

}
