#admin:
#    resource: "@AdminBundle/Controller/"
#    type:     annotation
#    prefix:   /

app:
    resource: '@PostBundle/Controller/'
    type: annotation
    prefix: /

user:
    resource: '@UserBundle/Controller/'
    type: annotation
    prefix: /


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin