<?php

namespace PaymentBundle\Repository;

/**
 * SBOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SBOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
