<?php

namespace PostBundle\Repository;

use Doctrine\ORM\AbstractQuery;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findApiCats($query){
        $qb = $this->createQueryBuilder('c')
            ->where('c.name like :name')
            ->setParameter('name', $query . '%')
            ->setMaxResults(8);

        $query = $qb->getQuery();

        return $query->getResult(AbstractQuery::HYDRATE_ARRAY);
    }

    public function getParentCats() {
        $qb = $this->createQueryBuilder('c')
            ->where('c.parent is null');

        return $qb;
    }

    public function getChildren($query) {
        $qb = $this->createQueryBuilder('c')
            ->where('c.parent = :parent')
            ->setParameter('parent', $query);

        $query = $qb->getQuery();

        return $query->getResult(AbstractQuery::HYDRATE_ARRAY);
    }
}
