<?php

namespace PostBundle\Repository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\AbstractQuery;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy([], ['createdAt' => 'DESC']);
    }

    public function findApiPosts($query){
        $qb = $this->createQueryBuilder('p')
            ->select('p.title as name')
            ->where('p.title like :title')
            ->setParameter('title', $query . '%')
            ->setMaxResults(8);

        $query = $qb->getQuery();

        return $query->getResult(AbstractQuery::HYDRATE_ARRAY);
    }
}
