<?php

namespace PostBundle\Repository;

use PostBundle\Entity\Tag;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $criteria
     * @return null|object|Tag
     */
    public function findTagOrCreate($criteria) {
        $entity = $this->findOneBy($criteria);

        if ($entity === null) {
            $entity = new Tag();
            $entity->setName($criteria['name']);
        }

        return $entity;
    }

    public function findBigTag()
    {
        $qb = $this->createQueryBuilder('t')
            ->innerJoin('t.posts', 'p')
            ->groupBy('t')
            ->select('count(p) as counts')
            ->orderBy('counts', 'DESC')
            ->setMaxResults(1);

        $query = $qb->getQuery();

        return $query->getOneOrNullResult();
    }
}
